[DEFAULT]
debian-branch = keel/trixie
upstream-branch = upstream/latest
upstream-tag = upstream/%(version)s
debian-tag = keel/%(version)s
debian-tag-msg = %(pkg)s Keel release %(version)s for trixie
pristine-tar = True
